### ISSUE TITLE
The performance issue of DomaiNet based on model resnet50.

### ISSUE THREAD

**Issue by qileee** [HCVLab/ProtoOT#1]
Hello, I am very interested in this work, but when I reproduced it, I found a problem. Although you provided the converged model, can you also provide the pre-trained model at the same time? cause I found that when I did not apply the pre-trained model, the performance kept fluctuating around 17

**Comment by HCVLab** [comment]
Hello, I appreciate your interest in this work. All experiments conducted here utilized the pre-trained model MoCo v2 800epoch. Here is the link to access the pre-trained model. [https://github.com/facebookresearch/moco?tab=readme-ov-file](url)

**Comment by HCVLab** [comment]
Hello, I appreciate your interest in this work. All experiments conducted here utilized the pre-trained model MocoV2 800epoch. Here is the link to access the pre-trained model.[https://github.com/facebookresearch/moco](url)

**Comment by HCVLab** [comment]
Hello, I appreciate your interest in this work. All experiments conducted here utilized the pre-trained model MocoV2 800epoch. Here is the link to access the pre-trained model.  

https://github.com/facebookresearch/moco

**Comment by HCVLab** [comment]
Hello, I appreciate your interest in this work. All experiments conducted here utilized the pre-trained model MocoV2 800 epochs. Here is the link to access the pre-trained model.

https://github.com/facebookresearch/moco
